package pack;

/*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/


/**
*
* @author codygulley
*/
public class TruthTable3 extends javax.swing.JFrame {

/**
* Creates new form Truthtable2
*/
public TruthTable3() {
initComponents();
}

/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code"> 
private void initComponents() {

panel = new javax.swing.JSplitPane();
Title = new javax.swing.JLabel();
ExitButton = new javax.swing.JButton();
jTextFieldPropP = new javax.swing.JTextField();
PropP = new javax.swing.JLabel();
jTextFieldPropQ = new javax.swing.JTextField();
PropQ = new javax.swing.JLabel();
AddProposition = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

Title.setText("Truth Table");

ExitButton.setText("Exit");
ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseReleased(java.awt.event.MouseEvent evt) {
Exit(evt);
}
public void mouseClicked(java.awt.event.MouseEvent evt) {
ExitButtonMouseClicked(evt);
}
});
ExitButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
ExitButtonActionPerformed(evt);
}
});

jTextFieldPropP.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextFieldPropPActionPerformed(evt);
}
});

PropP.setText("Proposition p : ");

jTextFieldPropQ.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextFieldPropQActionPerformed(evt);
}
});

PropQ.setText("Proposition q : ");

AddProposition.setText("Add Proposition");
AddProposition.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
AddPropositionMouseClicked(evt);
}
});
AddProposition.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
AddPropositionActionPerformed(evt);
}
});

org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
.add(layout.createSequentialGroup()
.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
.add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.add(ExitButton))
.add(layout.createSequentialGroup()
.add(258, 258, 258)
.add(Title)
.add(0, 0, Short.MAX_VALUE)))
.addContainerGap())
.add(layout.createSequentialGroup()
.add(74, 74, 74)
.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
.add(layout.createSequentialGroup()
.add(6, 6, 6)
.add(AddProposition))
.add(layout.createSequentialGroup()
.add(PropQ)
.add(40, 40, 40)
.add(jTextFieldPropQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
.add(layout.createSequentialGroup()
.add(PropP)
.add(40, 40, 40)
.add(jTextFieldPropP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
.addContainerGap(224, Short.MAX_VALUE))
);
layout.setVerticalGroup(
layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
.add(layout.createSequentialGroup()
.add(Title)
.add(43, 43, 43)
.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
.add(PropP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.add(jTextFieldPropP))
.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
.add(PropQ, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.add(jTextFieldPropQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
.add(AddProposition)
.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 163, Short.MAX_VALUE)
.add(ExitButton)
.addContainerGap())
);

pack();
}// </editor-fold> 

public void addbutton(){

}


private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) { 
// TODO add your handling code here:
} 

private void Exit(java.awt.event.MouseEvent evt) { 
System.exit(0);
} 

private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) { 
System.exit(0);
} 

private void jTextFieldPropPActionPerformed(java.awt.event.ActionEvent evt) { 
// TODO add your handling code here:
} 

private void jTextFieldPropQActionPerformed(java.awt.event.ActionEvent evt) { 
// TODO add your handling code here:
} 
private void jTextFieldPropRActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
private void AddPropositionActionPerformed(java.awt.event.ActionEvent evt) { 
// TODO add your handling code here:
} 

private void AddPropositionMouseClicked(java.awt.event.MouseEvent evt) { 
PropR = new JLabel();

} 

/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(TruthTable3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(TruthTable3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(TruthTable3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(TruthTable3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new TruthTable3().setVisible(true);
}
});
}
// Variables declaration - do not modify 
private javax.swing.JButton AddProposition;
private javax.swing.JButton ExitButton;
private javax.swing.JLabel PropP;
private javax.swing.JLabel PropQ;
private javax.swing.JLabel Title;
private javax.swing.JTextField jTextFieldPropP;
private javax.swing.JTextField jTextFieldPropQ;
private javax.swing.JSplitPane panel;
// End of variables declaration 
private javax.swing.JLabel jLabelPropR;
private javax.swing.JTextField jTextFieldPropR;
private javax.swing.JLabel PropR;

}